/*
 * Original KhaiDocs code, MIT.
 *
 * Search over the curated icon set: matches the Tabler name, the group and a
 * few everyday synonyms.
 */

const SYNONYMS: Record<string, string> = {
  "file-text": "page document doc text",
  notebook: "journal diary notes",
  notes: "memo note",
  book: "read reading library",
  "book-2": "manual handbook guide",
  books: "library reading list",
  article: "blog post essay",
  news: "newsletter updates",
  script: "draft",
  writing: "write draft author",
  pencil: "edit write draft",
  "clipboard-list": "agenda meeting minutes",
  checklist: "todo tasks list",
  "list-check": "todo tasks done",
  checkbox: "todo task",
  "clipboard-check": "review approval done",
  target: "goal goals okr objective",
  flag: "milestone goal",
  trophy: "win achievement goal",
  rocket: "launch project startup",
  calendar: "date schedule plan week month",
  "calendar-event": "event meeting date",
  "calendar-week": "week weekly plan",
  clock: "time schedule hours",
  alarm: "reminder deadline",
  hourglass: "wait time deadline",
  "map-2": "plan roadmap",
  route: "roadmap path plan",
  compass: "direction strategy vision",
  "road-sign": "direction decision",
  presentation: "slides deck talk",
  "chart-line": "stats metrics analytics",
  "chart-bar": "stats metrics report",
  "chart-pie": "budget stats",
  "trending-up": "growth progress",
  "report-analytics": "report analytics dashboard kpi",
  coin: "money finance budget",
  cash: "money finance expense",
  wallet: "money finance budget spending",
  "credit-card": "payment money expense",
  receipt: "invoice expense bill",
  "pig-money": "savings money finance",
  "building-bank": "bank finance",
  briefcase: "work job business career",
  building: "company office org",
  users: "team people group crm",
  user: "person profile me",
  "user-circle": "profile person",
  "address-book": "contacts crm",
  "id-badge": "hr employee",
  mail: "email inbox letter",
  "message-circle": "chat comment",
  messages: "chat discussion",
  phone: "call contact",
  speakerphone: "announcement marketing",
  code: "dev development programming engineering",
  "terminal-2": "cli shell command",
  "brackets-angle": "html markup code",
  "git-branch": "git version",
  "git-pull-request": "pr review merge",
  database: "data db sql",
  server: "infra backend hosting",
  cloud: "infra hosting saas",
  api: "integration endpoint",
  bug: "issue defect error",
  tool: "fix maintenance",
  tools: "setup maintenance",
  settings: "config preferences",
  adjustments: "tune options",
  cpu: "hardware chip",
  "device-laptop": "computer",
  "device-mobile": "phone app",
  palette: "design art colors",
  brush: "design paint art",
  "color-swatch": "design colors brand",
  photo: "image picture",
  camera: "photo photography",
  movie: "film video watch",
  music: "song playlist",
  headphones: "podcast audio listen",
  microphone: "podcast voice audio",
  bulb: "idea ideas tip",
  sparkles: "magic ai new",
  brain: "think mind knowledge",
  flask: "experiment lab research science",
  atom: "science research physics",
  school: "learn course study education",
  certificate: "certificate course diploma",
  world: "global web language",
  plane: "travel trip flight",
  luggage: "travel trip packing",
  beach: "vacation holiday travel",
  mountain: "hike outdoors travel",
  tent: "camping outdoors",
  car: "drive vehicle",
  bike: "cycling sport",
  home: "house personal",
  bed: "sleep rest",
  coffee: "cafe break morning",
  "tools-kitchen-2": "food recipe cooking meal",
  "shopping-cart": "shopping groceries buy",
  gift: "present birthday wishlist",
  heart: "love favorite health",
  heartbeat: "health fitness",
  stethoscope: "health medical doctor",
  pill: "health medicine",
  run: "fitness exercise sport",
  barbell: "fitness gym workout",
  apple: "food nutrition health",
  leaf: "nature eco",
  plant: "garden nature growth",
  sun: "day weather summer",
  moon: "night sleep",
  star: "favorite important",
  bolt: "fast energy power",
  flame: "hot urgent fire",
  snowflake: "winter cold",
  umbrella: "weather insurance",
  paw: "pet animal",
  dog: "pet animal",
  cat: "pet animal",
  "device-gamepad-2": "games gaming play",
  puzzle: "game problem",
  dice: "game random",
  key: "password access secret",
  lock: "private secure password",
  shield: "security safety",
  archive: "old storage",
  box: "storage inventory",
  package: "delivery shipping product",
  inbox: "email triage",
  folder: "directory collection",
  "folder-open": "directory collection",
  tag: "label category",
  link: "url bookmark",
  paperclip: "attachment",
  search: "find research",
  eye: "watch view",
  bell: "notification reminder",
  help: "faq question support",
  "info-circle": "about information",
  "alert-triangle": "warning risk incident",
  "circle-check": "done complete approved",
  lifebuoy: "support help",
  hash: "channel number",
  at: "email mention",
  infinity: "forever loop",
};

/** Lower-case words an icon can be found by. */
export function iconSearchText(name: string, group: string): string {
  return `${name.replace(/-/g, " ")} ${group} ${SYNONYMS[name] ?? ""}`.toLowerCase();
}

export function filterIcons<T extends { name: string; group: string }>(
  icons: T[],
  query: string,
): T[] {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return icons;
  return icons.filter((icon) => {
    const text = iconSearchText(icon.name, icon.group);
    return words.every((word) => text.includes(word));
  });
}
