/*
 * Original KhaiDocs code, MIT.
 *
 * The curated line-icon set for page icons: monochrome icons from
 * @tabler/icons-react (MIT), stored as "ti:<name>:<colour>" (see
 * ./page-icon-codec). Names are Tabler's own icon names.
 */

import type { Icon } from "@tabler/icons-react";
import {
  IconFileText,
  IconNotebook,
  IconNotes,
  IconBook,
  IconBook2,
  IconBooks,
  IconBookmark,
  IconArticle,
  IconNews,
  IconScript,
  IconWriting,
  IconPencil,
  IconQuote,
  IconHighlight,
  IconClipboardList,
  IconChecklist,
  IconListCheck,
  IconCheckbox,
  IconClipboardCheck,
  IconListDetails,
  IconTarget,
  IconFlag,
  IconTrophy,
  IconRocket,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarWeek,
  IconClock,
  IconAlarm,
  IconHourglass,
  IconMap2,
  IconRoute,
  IconCompass,
  IconRoadSign,
  IconPresentation,
  IconChartLine,
  IconChartBar,
  IconChartPie,
  IconTrendingUp,
  IconReportAnalytics,
  IconCoin,
  IconCash,
  IconWallet,
  IconCreditCard,
  IconReceipt,
  IconPigMoney,
  IconBuildingBank,
  IconBriefcase,
  IconBuilding,
  IconUsers,
  IconUser,
  IconUserCircle,
  IconAddressBook,
  IconIdBadge,
  IconMail,
  IconMessageCircle,
  IconMessages,
  IconPhone,
  IconSpeakerphone,
  IconCode,
  IconTerminal2,
  IconBracketsAngle,
  IconGitBranch,
  IconGitPullRequest,
  IconDatabase,
  IconServer,
  IconCloud,
  IconApi,
  IconBug,
  IconTool,
  IconTools,
  IconSettings,
  IconAdjustments,
  IconCpu,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconPalette,
  IconBrush,
  IconColorSwatch,
  IconPhoto,
  IconCamera,
  IconMovie,
  IconMusic,
  IconHeadphones,
  IconMicrophone,
  IconBulb,
  IconSparkles,
  IconBrain,
  IconFlask,
  IconAtom,
  IconSchool,
  IconCertificate,
  IconWorld,
  IconPlane,
  IconLuggage,
  IconBeach,
  IconMountain,
  IconTent,
  IconCar,
  IconBike,
  IconHome,
  IconBed,
  IconCoffee,
  IconToolsKitchen2,
  IconShoppingCart,
  IconGift,
  IconHeart,
  IconHeartbeat,
  IconStethoscope,
  IconPill,
  IconRun,
  IconBarbell,
  IconApple,
  IconLeaf,
  IconPlant,
  IconSun,
  IconMoon,
  IconStar,
  IconBolt,
  IconFlame,
  IconSnowflake,
  IconUmbrella,
  IconPaw,
  IconDog,
  IconCat,
  IconDeviceGamepad2,
  IconPuzzle,
  IconDice,
  IconKey,
  IconLock,
  IconShield,
  IconArchive,
  IconBox,
  IconPackage,
  IconInbox,
  IconFolder,
  IconFolderOpen,
  IconTag,
  IconLink,
  IconPaperclip,
  IconSearch,
  IconEye,
  IconBell,
  IconHelp,
  IconInfoCircle,
  IconAlertTriangle,
  IconCircleCheck,
  IconLifebuoy,
  IconHash,
  IconAt,
  IconInfinity,
} from "@tabler/icons-react";

export type IconGroup =
  | "Docs"
  | "Tasks"
  | "Time"
  | "Plans"
  | "Finance"
  | "Work"
  | "Code"
  | "Design"
  | "Ideas"
  | "Travel"
  | "Life"
  | "Things";

export interface CuratedIcon {
  name: string;
  group: IconGroup;
  Icon: Icon;
}

export const CURATED_ICONS: CuratedIcon[] = [
  { name: "file-text", group: "Docs", Icon: IconFileText },
  { name: "notebook", group: "Docs", Icon: IconNotebook },
  { name: "notes", group: "Docs", Icon: IconNotes },
  { name: "book", group: "Docs", Icon: IconBook },
  { name: "book-2", group: "Docs", Icon: IconBook2 },
  { name: "books", group: "Docs", Icon: IconBooks },
  { name: "bookmark", group: "Docs", Icon: IconBookmark },
  { name: "article", group: "Docs", Icon: IconArticle },
  { name: "news", group: "Docs", Icon: IconNews },
  { name: "script", group: "Docs", Icon: IconScript },
  { name: "writing", group: "Docs", Icon: IconWriting },
  { name: "pencil", group: "Docs", Icon: IconPencil },
  { name: "quote", group: "Docs", Icon: IconQuote },
  { name: "highlight", group: "Docs", Icon: IconHighlight },
  { name: "clipboard-list", group: "Docs", Icon: IconClipboardList },
  { name: "checklist", group: "Tasks", Icon: IconChecklist },
  { name: "list-check", group: "Tasks", Icon: IconListCheck },
  { name: "checkbox", group: "Tasks", Icon: IconCheckbox },
  { name: "clipboard-check", group: "Tasks", Icon: IconClipboardCheck },
  { name: "list-details", group: "Tasks", Icon: IconListDetails },
  { name: "target", group: "Tasks", Icon: IconTarget },
  { name: "flag", group: "Tasks", Icon: IconFlag },
  { name: "trophy", group: "Tasks", Icon: IconTrophy },
  { name: "rocket", group: "Tasks", Icon: IconRocket },
  { name: "calendar", group: "Time", Icon: IconCalendar },
  { name: "calendar-event", group: "Time", Icon: IconCalendarEvent },
  { name: "calendar-week", group: "Time", Icon: IconCalendarWeek },
  { name: "clock", group: "Time", Icon: IconClock },
  { name: "alarm", group: "Time", Icon: IconAlarm },
  { name: "hourglass", group: "Time", Icon: IconHourglass },
  { name: "map-2", group: "Plans", Icon: IconMap2 },
  { name: "route", group: "Plans", Icon: IconRoute },
  { name: "compass", group: "Plans", Icon: IconCompass },
  { name: "road-sign", group: "Plans", Icon: IconRoadSign },
  { name: "presentation", group: "Plans", Icon: IconPresentation },
  { name: "chart-line", group: "Finance", Icon: IconChartLine },
  { name: "chart-bar", group: "Finance", Icon: IconChartBar },
  { name: "chart-pie", group: "Finance", Icon: IconChartPie },
  { name: "trending-up", group: "Finance", Icon: IconTrendingUp },
  { name: "report-analytics", group: "Finance", Icon: IconReportAnalytics },
  { name: "coin", group: "Finance", Icon: IconCoin },
  { name: "cash", group: "Finance", Icon: IconCash },
  { name: "wallet", group: "Finance", Icon: IconWallet },
  { name: "credit-card", group: "Finance", Icon: IconCreditCard },
  { name: "receipt", group: "Finance", Icon: IconReceipt },
  { name: "pig-money", group: "Finance", Icon: IconPigMoney },
  { name: "building-bank", group: "Finance", Icon: IconBuildingBank },
  { name: "briefcase", group: "Work", Icon: IconBriefcase },
  { name: "building", group: "Work", Icon: IconBuilding },
  { name: "users", group: "Work", Icon: IconUsers },
  { name: "user", group: "Work", Icon: IconUser },
  { name: "user-circle", group: "Work", Icon: IconUserCircle },
  { name: "address-book", group: "Work", Icon: IconAddressBook },
  { name: "id-badge", group: "Work", Icon: IconIdBadge },
  { name: "mail", group: "Work", Icon: IconMail },
  { name: "message-circle", group: "Work", Icon: IconMessageCircle },
  { name: "messages", group: "Work", Icon: IconMessages },
  { name: "phone", group: "Work", Icon: IconPhone },
  { name: "speakerphone", group: "Work", Icon: IconSpeakerphone },
  { name: "code", group: "Code", Icon: IconCode },
  { name: "terminal-2", group: "Code", Icon: IconTerminal2 },
  { name: "brackets-angle", group: "Code", Icon: IconBracketsAngle },
  { name: "git-branch", group: "Code", Icon: IconGitBranch },
  { name: "git-pull-request", group: "Code", Icon: IconGitPullRequest },
  { name: "database", group: "Code", Icon: IconDatabase },
  { name: "server", group: "Code", Icon: IconServer },
  { name: "cloud", group: "Code", Icon: IconCloud },
  { name: "api", group: "Code", Icon: IconApi },
  { name: "bug", group: "Code", Icon: IconBug },
  { name: "tool", group: "Code", Icon: IconTool },
  { name: "tools", group: "Code", Icon: IconTools },
  { name: "settings", group: "Code", Icon: IconSettings },
  { name: "adjustments", group: "Code", Icon: IconAdjustments },
  { name: "cpu", group: "Code", Icon: IconCpu },
  { name: "device-laptop", group: "Code", Icon: IconDeviceLaptop },
  { name: "device-mobile", group: "Code", Icon: IconDeviceMobile },
  { name: "palette", group: "Design", Icon: IconPalette },
  { name: "brush", group: "Design", Icon: IconBrush },
  { name: "color-swatch", group: "Design", Icon: IconColorSwatch },
  { name: "photo", group: "Design", Icon: IconPhoto },
  { name: "camera", group: "Design", Icon: IconCamera },
  { name: "movie", group: "Design", Icon: IconMovie },
  { name: "music", group: "Design", Icon: IconMusic },
  { name: "headphones", group: "Design", Icon: IconHeadphones },
  { name: "microphone", group: "Design", Icon: IconMicrophone },
  { name: "bulb", group: "Ideas", Icon: IconBulb },
  { name: "sparkles", group: "Ideas", Icon: IconSparkles },
  { name: "brain", group: "Ideas", Icon: IconBrain },
  { name: "flask", group: "Ideas", Icon: IconFlask },
  { name: "atom", group: "Ideas", Icon: IconAtom },
  { name: "school", group: "Ideas", Icon: IconSchool },
  { name: "certificate", group: "Ideas", Icon: IconCertificate },
  { name: "world", group: "Travel", Icon: IconWorld },
  { name: "plane", group: "Travel", Icon: IconPlane },
  { name: "luggage", group: "Travel", Icon: IconLuggage },
  { name: "beach", group: "Travel", Icon: IconBeach },
  { name: "mountain", group: "Travel", Icon: IconMountain },
  { name: "tent", group: "Travel", Icon: IconTent },
  { name: "car", group: "Travel", Icon: IconCar },
  { name: "bike", group: "Travel", Icon: IconBike },
  { name: "home", group: "Life", Icon: IconHome },
  { name: "bed", group: "Life", Icon: IconBed },
  { name: "coffee", group: "Life", Icon: IconCoffee },
  { name: "tools-kitchen-2", group: "Life", Icon: IconToolsKitchen2 },
  { name: "shopping-cart", group: "Life", Icon: IconShoppingCart },
  { name: "gift", group: "Life", Icon: IconGift },
  { name: "heart", group: "Life", Icon: IconHeart },
  { name: "heartbeat", group: "Life", Icon: IconHeartbeat },
  { name: "stethoscope", group: "Life", Icon: IconStethoscope },
  { name: "pill", group: "Life", Icon: IconPill },
  { name: "run", group: "Life", Icon: IconRun },
  { name: "barbell", group: "Life", Icon: IconBarbell },
  { name: "apple", group: "Life", Icon: IconApple },
  { name: "leaf", group: "Life", Icon: IconLeaf },
  { name: "plant", group: "Life", Icon: IconPlant },
  { name: "sun", group: "Life", Icon: IconSun },
  { name: "moon", group: "Life", Icon: IconMoon },
  { name: "star", group: "Life", Icon: IconStar },
  { name: "bolt", group: "Life", Icon: IconBolt },
  { name: "flame", group: "Life", Icon: IconFlame },
  { name: "snowflake", group: "Life", Icon: IconSnowflake },
  { name: "umbrella", group: "Life", Icon: IconUmbrella },
  { name: "paw", group: "Life", Icon: IconPaw },
  { name: "dog", group: "Life", Icon: IconDog },
  { name: "cat", group: "Life", Icon: IconCat },
  { name: "device-gamepad-2", group: "Life", Icon: IconDeviceGamepad2 },
  { name: "puzzle", group: "Life", Icon: IconPuzzle },
  { name: "dice", group: "Life", Icon: IconDice },
  { name: "key", group: "Things", Icon: IconKey },
  { name: "lock", group: "Things", Icon: IconLock },
  { name: "shield", group: "Things", Icon: IconShield },
  { name: "archive", group: "Things", Icon: IconArchive },
  { name: "box", group: "Things", Icon: IconBox },
  { name: "package", group: "Things", Icon: IconPackage },
  { name: "inbox", group: "Things", Icon: IconInbox },
  { name: "folder", group: "Things", Icon: IconFolder },
  { name: "folder-open", group: "Things", Icon: IconFolderOpen },
  { name: "tag", group: "Things", Icon: IconTag },
  { name: "link", group: "Things", Icon: IconLink },
  { name: "paperclip", group: "Things", Icon: IconPaperclip },
  { name: "search", group: "Things", Icon: IconSearch },
  { name: "eye", group: "Things", Icon: IconEye },
  { name: "bell", group: "Things", Icon: IconBell },
  { name: "help", group: "Things", Icon: IconHelp },
  { name: "info-circle", group: "Things", Icon: IconInfoCircle },
  { name: "alert-triangle", group: "Things", Icon: IconAlertTriangle },
  { name: "circle-check", group: "Things", Icon: IconCircleCheck },
  { name: "lifebuoy", group: "Things", Icon: IconLifebuoy },
  { name: "hash", group: "Things", Icon: IconHash },
  { name: "at", group: "Things", Icon: IconAt },
  { name: "infinity", group: "Things", Icon: IconInfinity },
];

const BY_NAME = new Map(CURATED_ICONS.map((icon) => [icon.name, icon.Icon]));

/** The component for a stored icon name, or null if it is not in the set. */
export function getCuratedIcon(name: string): Icon | null {
  return BY_NAME.get(name) ?? null;
}
